name: C/C++ CI

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      working-directory: vac-hooks
      run: msbuild vac-hooks.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:diag
    - name: ls
      run: ls
    - uses: actions/upload-artifact@v1
      with:
        name: Release
        path: vac-hooks/Release/vac-hooks.dll
